In [ ]:
def add1(x,y):
    return x+y

myname="ASH"

def divisableby2(num):
    if(num%2==0):
        return True
    return False


In [44]:
def ispowertwo(num):
    for i in range((num//2)+1):
        if(num==2**i):
            return True
    else:
        return False
num=4096
if(ispowertwo(num)):
    print(num,"is power of two")
else:
    print(num,"is not power of two")

4096 is power of two


In [7]:
def minimum_difference(li,m):
    mi_li=sorted(li)
    mini=100
    for i in range(len(li)):
        if(m+i<len(li)+1):
            arr_li=mi_li[i:m+i]
            min_value=min(arr_li)
            max_value=max(arr_li)
            print(min_value,max_value)
            if(max_value-min_value<mini):
                mini=max_value-min_value
                
    return mini
li1=[12,4,7,9,2,23,25,41,30,40,28,42,30,44,48,43,50]
m=7
print(sorted(li1))
minimum_difference(li1,m)

[2, 4, 7, 9, 12, 23, 25, 28, 30, 30, 40, 41, 42, 43, 44, 48, 50]
2 25
4 28
7 30
9 30
12 40
23 41
25 42
28 43
30 44
30 48
40 50


10

In [3]:
print(3%5)

3


In [6]:
import numpy as np

In [7]:
def appendnm(arr):
    arr.append(4)
arr=[1,2,3]
print(arr)
appendnm(arr)
print(arr)

[1, 2, 3]
[1, 2, 3, 4]


In [8]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
print(np.rot90(np.rot90(arr,k=3,axes=(1,0))))

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [8]:
nums = [0,2,1,5,3,4]

print(ans)

[0, 1, 2, 4, 5, 3]


In [ ]:
operations =["X++","++X","--X","X--"]
X=0
for i in range(len(operations)):
    if(operations[i]=="X++" or operations[i]=="++X"):
        X+=1
    if(operations[i]=="X--" or operations[i]=="--X"):
        X-=1
print(X)

In [2]:
print(12<<2)

48


In [5]:
a=32
b=27
res=13
count=0
while((res&res-1)!=0):
    count+=1
    res=res&res-1
print(count)

2
